### ISSUE TITLE
Unmarshal failed to openAI spec

### ISSUE THREAD

**Issue by clockfly** [swaggest/openapi-go#114]
**Describe the bug**
Unmarshal yaml failed for https://github.com/openai/openai-openapi/blob/master/openapi.yaml

Error:
```
oneOf constraint failed for SchemaOrRef with 0 valid results: map[Schema:oneOf constraint failed for SchemaOrRef with 0 valid results: map[Schema:additional properties not allowed in Schema: [$ref] SchemaReference:additional properties not allowed in SchemaReference: [nullable]] SchemaReference:required key missing: $ref]

```

**To Reproduce**

```
yamlFile = "path_to_openapi.yaml"
bytes, _ := ioutil.ReadFile(yamlFile)
spec.UnmarshalYAML(bytes); err != nil {
	fmt.Println(err)
}
```

**Expected behavior**
This file should be parsed correctly. This file renders correctly in swagger editor.

https://editor-next.swagger.io/
<img width="1221" alt="image" src="https://github.com/swaggest/openapi-go/assets/2595532/d1213f59-a460-47ae-b6a2-a442d27e7b88">

**Additional context**
None

**Comment by vearutop** [comment]
The spec in question is not a valid one.

If you open it in a schema-enabled editor, like the one included in intellij IDEs (e.g. GoLand), you'll see warnings.
![image](https://github.com/swaggest/openapi-go/assets/1381436/b3fde8e2-f2fe-49c0-92c5-222a0316df33)

The issue here is that OpenAPI 3.0 is based on JSON Schema draft 04, which does not allow any fields adjacent to `$ref`.
This is also what is told by unmarshal error message (in a cryptic way though): 
```
additional properties not allowed in SchemaReference: [nullable]]
```

Here are original and fixed schemas:
[openai-openapi.json](https://github.com/swaggest/openapi-go/files/15499903/openai-openapi.json) Converted from the YAML original.
[openai-openapi-fixed.json](https://github.com/swaggest/openapi-go/files/15499902/openai-openapi-fixed.json) Fixed to pass unmarshaling.
